// <auto-generated />
using GmailCleaner.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GmailCleaner.Common.DataContext.SqlServer.Migrations
{
    [DbContext(typeof(GmailCleanerContext))]
    [Migration("20231202182501_gc12.2.23-1")]
    partial class gc122231
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GmailCleaner.Common.Models.User", b =>
                {
                    b.Property<int>("GmailId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GmailId")
                        .HasName("PK__Users__EAD496F534ED7B23");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
